# Generated by Django 3.0.3 on 2020-08-17 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('res_address', models.CharField(max_length=200)),
                ('personal_contact_no', models.CharField(max_length=10)),
                ('emergency_contact_no', models.CharField(max_length=10)),
                ('personal_email', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(choices=[('Analyst', 'Analyst'), ('Associate', 'Associate'), ('Senior Analyst', 'Senior Analyst'), ('Project Manager', 'Project Manager'), ('Human Resources', 'Human Resources')], default='Associate', max_length=100)),
                ('salary', models.FloatField()),
                ('passport_pic', models.ImageField(upload_to='passport_pic/')),
                ('joining_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
